---
#Configuration for PocketRPG plugin

#Level you want the RPG to work in:
RPGworld: ""

#Decide if block placing in RPG world is allowed (OPs will always be able to):
AllowBlockPlacing: false

#Decide if block breaking in RPG world is allowed (OPs will always be able to):
AllowBlockBreaking: false

#Message sent to players when a player reaches level 10:
LevelUpMessage: ""

#Switch for not being able to lose items in RPG world (crafting, furnace smelting, dropping etc...):
DisableItemLosing: true
...
